version: "3.2"
#
# Spin up an instance of the Model FHIR Proxy
#
# cd run
# docker-compose up
# (docker-compose up -d)
#
# OR via npm
#
# cd /
# npm run proxy:up
# (npm run proxy:up:detached)
#
services:

  proxy:
    image: synaneticsltd/synfhir-store-windows:latest
    container_name: proxy
    env_file:
       - ../proxy.env
    ports:
      - 3001:3000
    depends_on: 
      - localdb
    
