version: "3.2"
#
# Spin up an instance of the Model FHIR Proxy
#
# cd run
# docker-compose up
# (docker-compose up -d)
#
# OR via npm
#
# cd /
# npm run proxy:up
# (npm run proxy:up:detached)
#
services:

  proxy:
    image: synaneticsltd/synfhir-store:windows-2016-latest
    restart: always
    environment: 
      - NAMESPACE=synfhir-store
      - METRICSENABLE=false
      - PORT=3000
      - SERVICEDIR=services
    env_file:
       - ../proxy.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=PathPrefix(`/fhir`)"
      - "traefik.http.services.proxy.loadbalancer.server.port=3000"
      - "traefik.http.routers.proxy.entrypoints=secure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.domains[0].main=fhir.local"
    networks:
        - internal

  proxy-ssl:
    image: synaneticsltd/synfhir-windows-traefik:ltsc2016
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    depends_on: 
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../ssl/certs/:/etc/traefik/certs
      - ../../ssl/config/static.toml:/etc/traefik/traefik.toml
      - ../../ssl/config/dynamic.toml:/etc/traefik/dynamic_conf.toml
    networks:
      - internal
      - default
  
networks:
  internal:
  default:
    external:
      name: nat
    
