version: "3.2"
#
# Spin up an instance of the Model FHIR Proxy
#
# cd run
# docker-compose up
# (docker-compose up -d)
#
# OR via npm
#
# cd /
# npm run proxy:up
# (npm run proxy:up:detached)
#
services:

  proxy:
    image: synaneticsltd/synfhir-store:windows-2016-latest
    container_name: proxy
    restart: always
    environment: 
      - NAMESPACE=synfhir-store
      - METRICSENABLE=false
      - PORT=3000
      - SERVICEDIR=services
    env_file:
       - ../../proxy.env
    ports:
       - 3001:3000
    networks:
      - default

  proxy-ssl:
    image: synaneticsltd/synfhir-windows-traefik:ltsc2016
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on: 
      - proxy
    volumes:
      - ../../../ssl/certs:C:\etc\traefik\certs
      - ../../../ssl/config/windows/2016:C:\etc\traefik
    networks:
      - default